config/routes.rb
Rails.application.routes.draw do
  root 'listings#index'
  resources :listings, only: [:index, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index 
    @listings = Listing.all 
  end 

  def new 
    @listing = Listing.new
  end 

  def create 
    @Listing.create(listing_params)
    redirect_to root_path 
  end 

  private 

  def listing_params
    params.require(:listing),permit(:address, :description, :price)

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiztwo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Nashville Homes for Sale", root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item">
        <%= link_to 'New Listing', new_listing_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<% @listings.each do |listing| %>
  <div class="booyah-box col-10 offset-1"> 
    <h1><%= listing.address %></h1><br />
    <i><%= listing.description %></i><br /> 
    <p><%= listing.price %></p><br />
  </div>

  <hr />
  <% end %>

app/views/listings/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 style="font-family:Georgia;"> List Your Home </h1>
    <br /> 
    <%= simple_form_for @listing, url: listings_path do |f| %>
      <%= f.input :address %>
      <%= f.input :description %> 
      <%= f.input :price %>
      <br /> 
      <%= f.submit 'List', class: 'btn btn-primary' %>
    <% end %>
</div>